name: Google Play

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules # 👈 path for node_modules folder
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          # 👆 name of the chache key includes package-lock.json
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        # 👆 if cache hits the skip this step.
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB_ACTION }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Build
        run: ng build --configuration android-prod --base-href ./
      - name: Copy
        run: npx cap copy android
      - name: Bundle
        run: cd android && gradle bundleRelease
      - name: Upload release bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 60
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: io.github.mvolkert.dancingmoves
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: beta
          status: inProgress
